### PR TITLE
Update to last AC rev

### PR DESCRIPTION
**Pull request by d3athbl0w**

### CODE REVIEW

**Comment by darkenam** [comment]
Hi

Have error build in to last version


/azerothcore/modules/anticheat/src/AnticheatData.cpp: In member function ‘bool AnticheatData::CheckOnFlyHack()’:
/azerothcore/modules/anticheat/src/AnticheatData.cpp:217:24: error: ‘class Unit’ has no member named ‘GetTheClosestPoint’; did y              ou mean ‘GetClosePoint’?
  217 |                 mover->GetTheClosestPoint(cx, cy, cz, 0.5, pz, 6.8f); // first check
      |                        ^~~~~~~~~~~~~~~~~~
      |                        GetClosePoint
[ 98%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/anticheat/src/AnticheatMgr.cpp.o

**Comment by darkenam** [comment]
Hi

Have error build in to last version

https://github.com/UltraNix/mod-anticheat/tree/3d0be44e3142e7a95eb20dfe6583820c47c09720

/azerothcore/modules/anticheat/src/AnticheatData.cpp: In member function ‘bool AnticheatData::CheckOnFlyHack()’:
/azerothcore/modules/anticheat/src/AnticheatData.cpp:217:24: error: ‘class Unit’ has no member named ‘GetTheClosestPoint’; did y ou mean ‘GetClosePoint’?
217 | mover->GetTheClosestPoint(cx, cy, cz, 0.5, pz, 6.8f); // first check
| ^~~~~~~~~~~~~~~~~~
| GetClosePoint
[ 98%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir///__/modules/anticheat/src/AnticheatMgr.cpp.o

**Comment by UltraNix** [comment]
Why are you try to update that fork? Just use proper PR: https://github.com/azerothcore/azerothcore-wotlk/pull/6378

**Comment by darkenam** [comment]
@UltraNix  I usage this versions:

https://github.com/azerothcore/azerothcore-wotlk/pull/6378
and this mod
https://github.com/d3athbl0w/mod-anticheat/tree/ccf290f50025b35c337cbdfd3a94aea0b0e0b09d

but build have error:
/core/modules/anticheat/src/AnticheatScripts.cpp:56:10: error: ‘bool AnticheatPlayerScript::AnticheatHandleDoubleJump(Player*, Unit*)’ marked ‘override’, but does not override
   56 |     bool AnticheatHandleDoubleJump(Player* player, Unit* mover) override
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
/core/modules/anticheat/src/AnticheatScripts.cpp:61:10: error: ‘bool AnticheatPlayerScript::AnticheatCheckMovementInfo(Player*, const MovementInfo&, Unit*, bool)’ marked ‘override’, but does not override
   61 |     bool AnticheatCheckMovementInfo(Player* player, MovementInfo const& movementInfo, Unit* mover, bool jump) override
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:8374: src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/anticheat/src/AnticheatData.cpp.o] Error 1

**Pull request closed without merging**
